apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: app
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
      name: http
    - protocol: TCP
      port: 8443
      targetPort: https
      name: https
  type: ClusterIP
